stages:
  - build


build::docker:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --file docker/Dockerfile --tag "$CI_REGISTRY_IMAGE" . 
    - docker push "$CI_REGISTRY_IMAGE"