stages:
  - build

build::docker:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --file docker/x86/Dockerfile --tag "$CI_REGISTRY_IMAGE" . 
    - docker push "$CI_REGISTRY_IMAGE"

build::docker_rpi:
  tags:
    - rpi1
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --file docker/rpi/Dockerfile --tag "$CI_REGISTRY_IMAGE" . 
    - docker push "$CI_REGISTRY_IMAGE"
